import type { Metadata } from "next";
import {
  // Geist, Geist_Mono
  Lora,
  Lato
} from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import './../assets/css/Style.css';

/*const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});*/

// Define the font
const lora = Lora({
  variable: "--google-font-lora",
  subsets: ['latin'],
  weight: ['400', '500'], // Use a single weight, or an array: ['400', '700']
});
const lato = Lato({
  variable: "--google-font-lato",
  subsets: ['latin'],
  weight: ['400', '700'], // Use a single weight, or an array: ['400', '700']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lora.variable} ${lato.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
